### ISSUE TITLE
[Executor-LL] クオートするとバッファオーバーフロー

### ISSUE THREAD

**Issue by corvvs** [ryo-manba/minishell#21]
## 現象

```bash
% cat << "EOT"
<TOKEN{cat}'32'> <OP{<<}'32'> <TOKEN{"EOT"}'0'> <NEWLINE{\n}'0'> 
{Pipeline:
  {Clause:
    (<< {"EOT"}) 
    [WORD{cat}] 
  }
 }
=================================================================
==77229==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000050d6 at pc 0x00010653f3aa bp 0x7ffee96d0d70 sp 0x7ffee96d0d68
READ of size 1 at 0x6020000050d6 thread T0
Provided dSYM: [/Users/corvvs/reps/42cursus/minishell/mainflow/./minishell.dSYM/Contents/Resources/DWARF/minishell] does not match symbol owner 0x7fa95ec1efb0
    #0 0x10653f3a9 in ex_ll_unit ex_ll.c:86
    #1 0x10653fa0e in ex_shell_param ex_ll.c:109
    #2 0x10653cf58 in ms_expand_stree ms_expander.c:82
    #3 0x10653c697 in ms_expand_a_redir ms_expander.c:57
    #4 0x10654a520 in exec_expand_redirect exec_main_flow.c:57
    #5 0x10654b134 in exec_simple_redir exec_simple_cmd.c:107
    #6 0x10654afa9 in exec_simple_command exec_simple_cmd.c:81
    #7 0x10654a6d5 in ms_executer exec_main_flow.c:102
    #8 0x10653100c in mf_execute mf_repl.c:60
    #9 0x1065316fb in mf_loop mf_repl.c:88
    #10 0x10653074c in main ms_main.c:96
    #11 0x7fff64b413d4 in start (libdyld.dylib:x86_64+0x163d4)
```

**Comment by corvvs** [comment]
実はheredocに限らないっぽい
